# Generated by Django 6.0.2 on 2026-03-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_furniture_colors_furniture_depth_furniture_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_color', models.CharField(blank=True, max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('processing', 'Sedang Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bca', 'BCA'), ('bni', 'BNI'), ('bri', 'BRI'), ('mandiri', 'Mandiri')], default='bca', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan untuk pesanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('selected_color', models.CharField(blank=True, max_length=100)),
                ('furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.furniture')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='store.order')),
            ],
        ),
    ]
