# Generated by Django 6.0.2 on 2026-03-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Lengkap')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota/Kabupaten')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
