# Generated by Django 6.0.2 on 2026-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_payment_proof_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kelurahan'),
        ),
    ]
