# Generated by Django 6.0.2 on 2026-04-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='xendit_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xendit Invoice ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='xendit_invoice_url',
            field=models.URLField(blank=True, null=True, verbose_name='Xendit Invoice URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('xendit', 'Xendit Payment Gateway'), ('bca', 'BCA'), ('bni', 'BNI'), ('bri', 'BRI'), ('mandiri', 'Mandiri')], default='xendit', max_length=20, verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('awaiting_confirmation', 'Menunggu Konfirmasi'), ('paid', 'Sudah Dibayar'), ('processing', 'Sedang Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Selesai'), ('cancelled', 'Dibatalkan'), ('expired', 'Kedaluwarsa')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
