"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['store.interscienceid.com', 'localhost', '127.0.0.1']

# Disable COOP header so AR (Scene Viewer / Quick Look) can work on mobile
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog.apps.CatalogConfig',
    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'store.validators.AlphanumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('id', _('Bahasa Indonesia')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'config' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

UNFOLD = {
    "SITE_TITLE": "SBN Store Admin",
    "SITE_HEADER": "SBN Store",
    "SHOW_LANGUAGES": True,
    "THEME": "light",
    "SITE_URL": "/",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Otentikasi dan Otorisasi"),
                "separator": False,
                "items": [
                    {
                        "title": _("Pengguna"),
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": _("Grup"),
                        "icon": "groups",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": _("Katalog"),
                "separator": True,
                "items": [
                    {
                        "title": _("Produk Furnitur"),
                        "icon": "chair",
                        "link": "/admin/catalog/furniture/",
                    },
                    {
                        "title": _("Kategori"),
                        "icon": "category",
                        "link": "/admin/catalog/category/",
                    },
                ],
            },
            {
                "title": _("Manajemen Toko"),
                "separator": True,
                "items": [
                    {
                        "title": _("Keranjang"),
                        "icon": "shopping_cart",
                        "link": "/admin/store/cart/",
                    },
                    {
                        "title": _("Pesanan"),
                        "icon": "receipt_long",
                        "link": "/admin/store/order/",
                    },
                    {
                        "title": _("Profil Pengguna"),
                        "icon": "person",
                        "link": "/admin/store/userprofile/",
                    },
                ],
            },
        ],
    },
    "SITE_LOGO": {
        "light": lambda request: "/media/sbn.png",
        "dark": lambda request: "/media/sbn.png",
    },
    "SITE_ICON": {
        "light": lambda request: "/media/sbn-logo.png",
        "dark": lambda request: "/media/sbn-logo.png",
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "type": "image/png",
            "href": "/media/sbn-logo.png",
        }
    ],
    "COLORS": {
        "primary": {
            "50": "#f2fbff",
            "100": "#d5f3ff",
            "200": "#c5e8f6",
            "300": "#aaccd9",
            "400": "#5fa3be",
            "500": "#4186a5",
            "600": "#376d89",
            "700": "#2a4b57",
            "800": "#1A3C47",
            "900": "#002631",
            "950": "#001f28",
        },
    },
}

# XENDIT CONFIGURATION
# Diambil dari environment variable (.env)
XENDIT_SECRET_KEY = os.getenv('XENDIT_SECRET_KEY', '')
XENDIT_WEBHOOK_TOKEN = os.getenv('XENDIT_WEBHOOK_TOKEN', '')

