# Generated by Django 6.0.2 on 2026-02-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('model_glb', models.FileField(help_text='3D model for Android/WebXR (.glb)', upload_to='models/glb/')),
                ('model_usdz', models.FileField(blank=True, help_text='3D model for iOS AR (.usdz)', null=True, upload_to='models/usdz/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='catalog.category')),
            ],
        ),
    ]
