# Generated by Django 6.0.2 on 2026-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='colors',
            field=models.CharField(blank=True, help_text='Pilihan warna, pisahkan dengan koma (contoh: Coklat, Hitam, Putih)', max_length=300),
        ),
        migrations.AddField(
            model_name='furniture',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kedalaman/Panjang dalam cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tinggi dalam cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Harga dalam Rupiah (IDR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='furniture',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah stok tersedia'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Lebar dalam cm', max_digits=8, null=True),
        ),
    ]
