# Generated by Django 6.0.2 on 2026-03-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_furniture_colors_furniture_depth_furniture_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Produk Furnitur', 'verbose_name_plural': 'Produk Furnitur'},
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Foto Tambahan 2'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Foto Tambahan 3'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Foto Tambahan 4'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Foto Tambahan 5'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='video',
            field=models.FileField(blank=True, help_text='Unggah video peragaan/produk (opsional)', null=True, upload_to='videos/', verbose_name='Video Produk'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='catalog.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='colors',
            field=models.CharField(blank=True, help_text='Pilihan warna, pisahkan dengan koma (contoh: Coklat, Hitam, Putih)', max_length=300, verbose_name='Warna'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kedalaman/Panjang dalam cm', max_digits=8, null=True, verbose_name='Kedalaman/Panjang'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tinggi dalam cm', max_digits=8, null=True, verbose_name='Tinggi'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='model_glb',
            field=models.FileField(help_text='3D model for Android/WebXR (.glb)', upload_to='models/glb/', verbose_name='Model 3D (.glb)'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='model_usdz',
            field=models.FileField(blank=True, help_text='3D model for iOS AR (.usdz)', null=True, upload_to='models/usdz/', verbose_name='Model 3D (.usdz)'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Produk'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Harga dalam Rupiah (IDR)', max_digits=12, verbose_name='Harga'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah stok tersedia', verbose_name='Stok'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='Foto Utama'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Lebar dalam cm', max_digits=8, null=True, verbose_name='Lebar'),
        ),
    ]
