# Generated by Django 6.0.2 on 2026-03-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_furniture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='stock',
        ),
        migrations.CreateModel(
            name='FurnitureVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Warna Merah, Ukuran L, Set Besi', max_length=150, verbose_name='Nama Varian')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.furniture', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Varian',
                'verbose_name_plural': 'Varian',
            },
        ),
    ]
